### ISSUE TITLE
FuzzyDate intermittently fails to trigger

### ISSUE THREAD

**Issue by Stvad** [roam-unofficial/roam-toolkit#32]
Illustration: https://www.dropbox.com/s/s42ejiqo7ilev4g/roamextension.gif

Notes:
* Windows 10
* Both Chrome & FF
* Incognito mode helps, but not all the way
* Textexpander installed on the system

Full discussion here: https://www.reddit.com/r/RoamResearch/comments/fjofcr/roam_toolkit_a_browser_extension_for_roam_that/

For now I'm clueless about this one =\

**Comment by thesved** [comment]
The problem is with keyboard layouts where you have to press multiple keys to get a `;` character, for me it is `alt + ,`

**If I release the `alt` key too fast**, the system still has `;` for `keydown` and `keypress`, but it produces 2 separate keyups, one `alt` and one `,`.

See: https://www.dropbox.com/s/n8byj2nc9jvpcnm/Screen%20Recording%202020-05-15%20at%2015.46.24.mov?dl=0

The solution is to replace the `keydown` listener with `keypress`.

**Comment by Stvad** [comment]
ah, ok, I didn't see that one coming. I supposed I should make Guard configurable at some point too..
