### ISSUE TITLE
Integrate Twitter & Hypothes.is extraction into the toolkit

### ISSUE THREAD

**Issue by Stvad** [roam-unofficial/roam-toolkit#36]
@houshuang extracting roam compatible data from twitter/hypothesis

    hopefully this will make it easier for other people to build similar integrations. + eventually when API is there this can ingest things directly to roam
    also maybe we can have it authenticate with twitter properly. right now process is scary

@houshuang presumably we can do OAuth, which would greatly simplify credentials UX

I'd be happy with the "copy in roam format" functionality as a starting point (similar to what you have atm).

@dalmo3 https://github.com/dalmo3/hypothesis-to-bullets-chrome-extension

**Comment by thesved** [comment]
Authentication may not be necessary since we only need Twitter -> Roam, and not the other way around.

Instapaper adds a button to tweets, and it doesn't look that complicated:
<img width="591" alt="instapaper" src="https://user-images.githubusercontent.com/2893181/82473630-2a2ec180-9aca-11ea-9ec4-39bd305d7725.png">

**Comment by Stvad** [comment]
I know I created this issue, but I'm not sure anymore if it's a good fit. There is a bunch of highlighter/web-clipper like extensions out there for Roam, may be a better fit for them. Gonna close this for now
