### ISSUE TITLE
Add "jitter" to SRS algorithm implementation

### ISSUE THREAD

**Issue by Stvad** [roam-unofficial/roam-toolkit#38]
So you don't get the clusters of notes always "traveling together in time"

**Comment by houshuang** [comment]
This seems like it would be pretty easy - even something less than perfect would be great, just so that if I add a few items at the same time (very common), and always vote for example 4, that they don't always follow each other... (It's OK if they follow each other the first repetition if that is the next day, but then it should diverge).

**Comment by Stvad** [comment]
I actually have it implemented locally 😅. I haven't pushed it because it was breaking tests, but I'll finalize it in the next few days
